"""Exam indexer - indexes PDFs to ChromaDB."""

import chromadb
from pathlib import Path
from typing import Optional
from loguru import logger

from models.chunk import Chunk
from models.exam import Exam
from core.chunking import chunk_pdf


class ExamIndexer:
    """Indexes exam PDFs to ChromaDB."""

    def __init__(self, persist_directory: str = "data/chroma"):
        """
        Initialize the indexer.

        Args:
            persist_directory: Directory for ChromaDB persistence
        """
        self.persist_directory = persist_directory
        self.client = chromadb.PersistentClient(path=persist_directory)
        self.collection = None

    def get_or_create_collection(self, name: str = "exam_chunks"):
        """Get or create a ChromaDB collection."""
        self.collection = self.client.get_or_create_collection(
            name=name,
            metadata={"description": "Haitian Baccalaureate exam chunks"}
        )
        return self.collection

    def index_pdf(self, pdf_path: str | Path, llm_client=None) -> list[Chunk]:
        """
        Index a PDF file to ChromaDB.

        Args:
            pdf_path: Path to the PDF file
            llm_client: Optional LLM client for smart chunking

        Returns:
            List of created chunks
        """
        pdf_path = Path(pdf_path)
        logger.info(f"Indexing PDF: {pdf_path}")

        # Get or create collection
        self.get_or_create_collection()

        # Chunk the PDF
        chunks = chunk_pdf(pdf_path, llm_client)

        # Add to ChromaDB
        self._add_chunks(chunks)

        logger.info(f"Indexed {len(chunks)} chunks from {pdf_path.name}")
        return chunks

    def _add_chunks(self, chunks: list[Chunk]):
        """Add chunks to ChromaDB."""
        if not chunks:
            return

        # Prepare for ChromaDB
        ids = []
        embeddings = []  # Would be generated by embedding model
        documents = []
        metadatas = []

        for i, chunk in enumerate(chunks):
            chunk_id = f"{Path(chunk.exam_file).stem}_{i}"
            ids.append(chunk_id)
            documents.append(chunk.to_text())
            metadatas.append(chunk.to_metadata_dict())

        # Add to collection (without embeddings for now - would use embedding model)
        self.collection.add(
            ids=ids,
            documents=documents,
            metadatas=metadatas
        )

    def search(
        self,
        query: str,
        n_results: int = 5,
        filters: Optional[dict] = None
    ) -> list[dict]:
        """
        Search the index.

        Args:
            query: Search query
            n_results: Number of results to return
            filters: Optional metadata filters

        Returns:
            List of search results
        """
        if not self.collection:
            self.get_or_create_collection()

        results = self.collection.query(
            query_texts=[query],
            n_results=n_results,
            where=filters
        )

        # Format results
        formatted = []
        for i in range(len(results["documents"][0])):
            formatted.append({
                "content": results["documents"][0][i],
                "metadata": results["metadatas"][0][i],
                "distance": results["distances"][0][i] if "distances" in results else None
            })

        return formatted

    def get_stats(self) -> dict:
        """Get index statistics."""
        if not self.collection:
            self.get_or_create_collection()

        return {
            "total_chunks": self.collection.count(),
            "collection_name": self.collection.name
        }

    def delete_exam(self, exam_file: str):
        """Delete all chunks for a specific exam file."""
        if not self.collection:
            self.get_or_create_collection()

        # Get all IDs for this exam
        exam_stem = Path(exam_file).stem
        all_ids = self.collection.get()["ids"]
        to_delete = [id for id in all_ids if id.startswith(exam_stem)]

        if to_delete:
            self.collection.delete(ids=to_delete)
            logger.info(f"Deleted {len(to_delete)} chunks for {exam_file}")


def index_pdf(pdf_path: str | Path, persist_directory: str = "data/chroma") -> list[Chunk]:
    """Convenience function to index a PDF."""
    indexer = ExamIndexer(persist_directory)
    return indexer.index_pdf(pdf_path)


if __name__ == "__main__":
    # Test indexing
    import sys

    if len(sys.argv) > 1:
        pdf_path = sys.argv[1]
        indexer = ExamIndexer()

        # Index PDF (without LLM for now)
        chunks = indexer.index_pdf(pdf_path)

        print(f"Indexed {len(chunks)} chunks")

        # Show stats
        print(f"Total in index: {indexer.get_stats()}")
